export const el = {
  openOrderBtns: document.querySelectorAll('[data-order-trigger]'),
  landingProductGrids: document.querySelectorAll('[data-menu-category]'),
  announcement: document.getElementById('order-announcement'),
  orderBarMeta: document.getElementById('order-bar-meta'),
  orderSheet: document.getElementById('order-sheet'),
  orderBackdrop: document.getElementById('order-backdrop'),
  closeOrderBtn: document.getElementById('close-order-sheet'),
  stepBtns: document.querySelectorAll('.order-step'),
  panels: document.querySelectorAll('.order-panel'),
  orderSheetScroll: document.getElementById('order-sheet-scroll'),
  categoryChips: document.getElementById('category-chips'),
  productGrid: document.getElementById('product-grid'),
  cartList: document.getElementById('cart-list'),
  cartEmpty: document.getElementById('cart-empty'),
  orderSubtotal: document.getElementById('order-subtotal'),
  orderPackaging: document.getElementById('order-packaging'),
  orderShippingDistanceRow: document.getElementById('order-shipping-distance-row'),
  orderShippingDistance: document.getElementById('order-shipping-distance'),
  orderShipping: document.getElementById('order-shipping'),
  orderTotal: document.getElementById('order-total'),
  nextBtn: document.getElementById('order-next-btn'),
  sendBtn: document.getElementById('send-order-btn'),
  helper: document.getElementById('order-helper'),
  customerName: document.getElementById('customer-name'),
  customerAddress: document.getElementById('customer-address'),
  customerBetweenStreets: document.getElementById('customer-between-streets'),
  customerReferences: document.getElementById('customer-references'),
  customerNotes: document.getElementById('customer-notes'),
  geoBtn: document.getElementById('geo-btn'),
  mapPickerBtn: document.getElementById('map-picker-btn'),
  geoStatus: document.getElementById('geo-status'),
  mapPickerBackdrop: document.getElementById('map-picker-backdrop'),
  mapPickerModal: document.getElementById('map-picker-modal'),
  closeMapPickerBtn: document.getElementById('close-map-picker'),
  cancelMapPickerBtn: document.getElementById('cancel-map-picker-btn'),
  confirmMapPickerBtn: document.getElementById('confirm-map-picker-btn'),
  mapPickerStatus: document.getElementById('map-picker-status'),
  locationMap: document.getElementById('location-map'),
  orderTypeInputs: document.querySelectorAll('input[name="order-type"]'),
  orderTypeSections: document.querySelectorAll('[data-order-section]'),
  pickupTime: document.getElementById('pickup-time'),
  configSheet: document.getElementById('config-sheet'),
  configBackdrop: document.getElementById('config-backdrop'),
  configTitle: document.getElementById('config-title'),
  configName: document.getElementById('config-product-name'),
  configPrice: document.getElementById('config-product-price'),
  configOptions: document.getElementById('config-options'),
  configQty: document.getElementById('config-qty'),
  configError: document.getElementById('config-error'),
  configQtyDec: document.getElementById('config-qty-dec'),
  configQtyInc: document.getElementById('config-qty-inc'),
  closeConfigBtn: document.getElementById('close-config-sheet'),
  cancelConfigBtn: document.getElementById('cancel-config-btn'),
  addConfigBtn: document.getElementById('add-config-btn'),
};

export const revealItems = document.querySelectorAll('.reveal');
export const nav = document.querySelector('.main-nav');
export const navToggle = document.querySelector('.nav-toggle');
export const navLinks = document.querySelectorAll('.main-nav .nav-links a');
export const sections = document.querySelectorAll('section[id]');
