window.MENU_DATA = {
  timezone: 'America/Mexico_City',
  businessLocation: {
    lat: 19.27681612979457,
    lng: -99.17129268331983,
    label: 'Cocina La Abundancia',
  },
  pricing: {
    deliveryPerKm: 10,
    packaging: {
      enabledFor: 'all_products',
      mode: 'per_item',
      amount: 10,
    },
    pickupCharge: {
      mode: 'fixed_per_order',
      amount: 0,
    },
    shipping: {
      mode: 'confirm_default_with_toggle_fixed',
      fixedAmount: 30,
    },
  },
  categories: [
    { id: 'desayunos', name: 'Desayunos', order: 1 },
    { id: 'carta', name: 'Menú a la carta', order: 2 },
    {
      id: 'pozole-pancita',
      name: 'Pozole y pancita',
      order: 3,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '10:00',
        end: '22:00',
      },
    },
    {
      id: 'antojitos',
      name: 'Antojitos',
      order: 4,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
    },
    { id: 'bebidas', name: 'Bebidas', order: 5 },
    { id: 'postres', name: 'Postres', order: 6 },
  ],
  products: [
    {
      id: 'des-chilaquiles',
      categoryId: 'desayunos',
      name: 'Chilaquiles con huevo o pollo',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-huevos-gusto',
      categoryId: 'desayunos',
      name: 'Huevos al gusto (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-enchiladas-verdes',
      categoryId: 'desayunos',
      name: 'Enchiladas verdes de pollo (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-enmoladas',
      categoryId: 'desayunos',
      name: 'Enmoladas (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-hotcakes',
      categoryId: 'desayunos',
      name: 'Hot cakes (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-molletes',
      categoryId: 'desayunos',
      name: 'Molletes (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-tacos-dorados',
      categoryId: 'desayunos',
      name: 'Tacos dorados de pollo (3 pz)',
      basePrice: 70,
      description: 'Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
      modifiers: [
        {
          id: 'des-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'chocolate', label: 'Chocolate caliente', priceDelta: 10 }],
        },
      ],
    },
    {
      id: 'des-pan-frances',
      categoryId: 'desayunos',
      name: 'Pan francés',
      basePrice: 70,
      description: 'Nuevos platillos · Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
    },
    {
      id: 'des-sandwich',
      categoryId: 'desayunos',
      name: 'Sándwich',
      basePrice: 70,
      description: 'Nuevos platillos · Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
    },
    {
      id: 'des-cuernitos',
      categoryId: 'desayunos',
      name: 'Cuernitos',
      basePrice: 70,
      description: 'Nuevos platillos · Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
    },
    {
      id: 'des-sincronizadas',
      categoryId: 'desayunos',
      name: 'Sincronizadas',
      basePrice: 70,
      description: 'Nuevos platillos · Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
    },
    {
      id: 'des-enfrijoladas',
      categoryId: 'desayunos',
      name: 'Enfrijoladas',
      basePrice: 70,
      description: 'Nuevos platillos · Incluye bebida y fruta o jugo',
      availability: { mode: 'always' },
    },

    {
      id: 'alc-enchiladas-verdes',
      categoryId: 'carta',
      name: 'Enchiladas verdes',
      basePrice: 100,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-enchiladas-huevo',
      categoryId: 'carta',
      name: 'Enchiladas con huevo',
      basePrice: 110,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-enchiladas-carne',
      categoryId: 'carta',
      name: 'Enchiladas con carne',
      basePrice: 130,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-enmoladas',
      categoryId: 'carta',
      name: 'Enmoladas',
      basePrice: 100,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-enmoladas-huevo',
      categoryId: 'carta',
      name: 'Enmoladas con huevo',
      basePrice: 110,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-enmoladas-carne',
      categoryId: 'carta',
      name: 'Enmoladas con carne',
      basePrice: 130,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-tacos-dorados',
      categoryId: 'carta',
      name: 'Tacos dorados',
      basePrice: 100,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-milanesa',
      categoryId: 'carta',
      name: 'Milanesa',
      basePrice: 100,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-pechuga-rellena',
      categoryId: 'carta',
      name: 'Pechuga rellena',
      basePrice: 130,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-carne-asada',
      categoryId: 'carta',
      name: 'Carne asada',
      basePrice: 100,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },
    {
      id: 'alc-papas-fritas',
      categoryId: 'carta',
      name: 'Papas fritas',
      basePrice: 35,
      description: 'Recipiente y envío se cotizan por separado',
      availability: { mode: 'always' },
    },

    {
      id: 'pozole',
      categoryId: 'pozole-pancita',
      name: 'Pozole',
      basePrice: 100,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '10:00',
        end: '22:00',
      },
    },
    {
      id: 'pancita',
      categoryId: 'pozole-pancita',
      name: 'Pancita',
      basePrice: 100,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '10:00',
        end: '22:00',
      },
    },

    {
      id: 'ant-quesadilla',
      categoryId: 'antojitos',
      name: 'Quesadilla',
      basePrice: 30,
      description: 'Preparación y relleno obligatorios',
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'quesa-preparacion',
          label: 'Preparación',
          type: 'single',
          required: true,
          options: [
            { id: 'comal', label: 'Al comal', priceDelta: 0 },
            { id: 'frita', label: 'Frita', priceDelta: 0 },
          ],
        },
        {
          id: 'quesa-relleno',
          label: 'Relleno',
          type: 'single',
          required: true,
          options: [
            { id: 'tinga', label: 'Tinga', priceDelta: 0 },
            { id: 'chicharron', label: 'Chicharrón', priceDelta: 0 },
            { id: 'champinones', label: 'Champiñones', priceDelta: 0 },
            { id: 'pancita', label: 'Pancita', priceDelta: 0 },
            { id: 'papas-rajas', label: 'Papas con rajas', priceDelta: 0 },
            { id: 'papas-longaniza', label: 'Papas con longaniza', priceDelta: 0 },
            { id: 'picadillo', label: 'Picadillo', priceDelta: 0 },
            { id: 'queso', label: 'Queso', priceDelta: 0 },
          ],
        },
        {
          id: 'quesa-extra',
          label: 'Extras',
          type: 'multi',
          required: false,
          options: [{ id: 'extra-queso', label: 'Queso extra', priceDelta: 5 }],
        },
      ],
    },
    {
      id: 'ant-gordita',
      categoryId: 'antojitos',
      name: 'Gordita',
      basePrice: 35,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'gordita-version',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'sencilla', label: 'Sencilla', priceDelta: 0 },
            { id: 'con-queso', label: 'Con queso', priceDelta: 5 },
            { id: 'especial', label: 'Especial', priceDelta: 15 },
          ],
        },
      ],
    },
    {
      id: 'ant-sope',
      categoryId: 'antojitos',
      name: 'Sope',
      basePrice: 30,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'sope-version',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'sencillo', label: 'Sencillo', priceDelta: 0 },
            { id: 'guisado', label: 'Con guisado', priceDelta: 10 },
            { id: 'carne', label: 'De carne', priceDelta: 15 },
            { id: 'especial', label: 'Especial', priceDelta: 20 },
          ],
        },
      ],
    },
    {
      id: 'ant-huarache',
      categoryId: 'antojitos',
      name: 'Huarache',
      basePrice: 60,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'huarache-version',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'sencillo', label: 'Sencillo', priceDelta: 0 },
            { id: 'guisado', label: 'Con guisado', priceDelta: 20 },
            { id: 'carne', label: 'De carne', priceDelta: 35 },
            { id: 'bistec', label: 'De bistec', priceDelta: 40 },
            { id: 'especial', label: 'Especial', priceDelta: 50 },
          ],
        },
      ],
    },
    {
      id: 'ant-pambazo',
      categoryId: 'antojitos',
      name: 'Pambazo',
      basePrice: 35,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
    },
    {
      id: 'ant-tostada',
      categoryId: 'antojitos',
      name: 'Tostada',
      basePrice: 35,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'tostada-tipo',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'tinga', label: 'Tinga', priceDelta: 0 },
            { id: 'picadillo', label: 'Picadillo', priceDelta: 0 },
            { id: 'pata', label: 'Pata', priceDelta: 0 },
            { id: 'papas-longaniza', label: 'Papas con longaniza', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'ant-taco',
      categoryId: 'antojitos',
      name: 'Taco',
      basePrice: 40,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'taco-tipo',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'suadero', label: 'Suadero', priceDelta: 0 },
            { id: 'pastor', label: 'Pastor', priceDelta: 0 },
            { id: 'bistec', label: 'Bistec', priceDelta: 5 },
          ],
        },
      ],
    },
    {
      id: 'ant-torta',
      categoryId: 'antojitos',
      name: 'Torta',
      basePrice: 30,
      availability: {
        mode: 'schedule',
        days: [5, 6],
        start: '16:00',
        end: '22:30',
      },
      modifiers: [
        {
          id: 'torta-tipo',
          label: 'Tipo',
          type: 'single',
          required: true,
          options: [
            { id: 'jamon', label: 'Jamón', priceDelta: 0 },
            { id: 'pastor', label: 'Pastor', priceDelta: 15 },
            { id: 'suadero', label: 'Suadero', priceDelta: 15 },
            { id: 'bistec', label: 'Bistec', priceDelta: 20 },
            { id: 'milanesa', label: 'Milanesa', priceDelta: 15 },
          ],
        },
      ],
    },

    { id: 'beb-refresco', categoryId: 'bebidas', name: 'Refresco', basePrice: 25, availability: { mode: 'always' } },
    { id: 'beb-cafe-te', categoryId: 'bebidas', name: 'Café o té', basePrice: 25, availability: { mode: 'always' } },
    { id: 'beb-agua-1l', categoryId: 'bebidas', name: 'Agua de sabor 1L', basePrice: 40, availability: { mode: 'always' } },
    { id: 'beb-agua-500ml', categoryId: 'bebidas', name: 'Agua de sabor 1/2L', basePrice: 20, availability: { mode: 'always' } },

    { id: 'post-flan', categoryId: 'postres', name: 'Flan', basePrice: 30, availability: { mode: 'always' } },
    { id: 'post-pay-limon', categoryId: 'postres', name: 'Pay de limón', basePrice: 30, availability: { mode: 'always' } },
    { id: 'post-cheesecake-oreo', categoryId: 'postres', name: 'Cheesecake de Oreo', basePrice: 30, availability: { mode: 'always' } },
  ],
};
